### PR TITLE
Removed more unneeded pointers

### PR DESCRIPTION
**Pull request by Kefta**
NOTHING TO SEE HERE

### CODE REVIEW

**Comment by Kefta** [comment]
Fucking dick hole

**Comment by aStonePenguin** [comment]
No need to flame

**Comment by KingofBeast** [comment]
Let's stop the fucking rollercoaster for a second.

There's something else I want to hit you with.

Shpiders.

**Comment by aStonePenguin** [comment]
[Oh shit on shit](https://www.youtube.com/watch?v=2fc4MHhIabA)

**Pull request closed without merging**
